module.exports = {
  'baltimore orioles': 'orioles',
  'boston red sox': 'red sox',
  'new york yankees': 'yankees',
  'tampa bay rays': 'rays',
  'toronto blue jays': 'blue jays',
  'chicago white sox': 'white sox',
  'cleveland indians': 'indians',
  'detroit tigers': 'tigers',
  'kansas city royals': 'royals',
  'minnesota twins': 'twins',
  'houston astros': 'astros',
  'los angeles angels': 'angels',
  'oakland athletics': 'athletics',
  'seattle mariners': 'mariners',
  'texas rangers': 'rangers',
  'atlanta braves': 'braves',
  'miami marlins': 'marlins',
  'new york mets': 'mets',
  'philadelphia phillies': 'phillies',
  'washington nationals': 'nationals',
  'chicago cubs': 'cubs',
  'cincinnati reds': 'reds',
  'milwaukee brewers': 'brewers',
  'pittsburgh pirates': 'pirates',
  'st. louis cardinals': 'cardinals',
  'arizona diamondbacks': 'd-backs',
  'colorado rockies': 'rockies',
  'los angeles dodgers': 'dodgers',
  'san diego padres': 'padres',
  'san francisco giants': 'giants',
  'orioles': 'orioles',
  'red sox': 'red sox',
  'yankees': 'yankees',
  'rays': 'rays',
  'blue jays': 'blue jays',
  'white sox': 'white sox',
  'indians': 'indians',
  'tigers': 'tigers',
  'royals': 'royals',
  'twins': 'twins',
  'astros': 'astros',
  'angels': 'angels',
  'athletics': 'athletics',
  'mariners': 'mariners',
  'rangers': 'rangers',
  'braves': 'braves',
  'marlins': 'marlins',
  'mets': 'mets',
  'phillies': 'phillies',
  'nationals': 'nationals',
  'cubs': 'cubs',
  'reds': 'reds',
  'brewers': 'brewers',
  'pirates': 'pirates',
  'cardinals': 'cardinals',
  'diamondbacks': 'd-backs',
  'rockies': 'rockies',
  'dodgers': 'dodgers',
  'padres': 'padres',
  'giants': 'giants',
};
